# Config for the Netlify Build Plugin: netlify-plugin-fetch-feeds
[build]
  base = "website"
  command = "npm i; npm run build"
  publish = "dist"

[[redirects]]
  # Redirect default Netlify subdomain to primary domain
  from = "https://dat-events.netlify.com/*"
  to = "https://events.dat.foundation/:splat"
  status = 301
  force = true

[[redirects]]
  # Redirect default Netlify subdomain to primary domain
  from = "https://events.datproject.org/*"
  to = "https://events.dat.foundation/:splat"
  status = 301
  force = true

[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = true
  minify = false
[build.processing.js]
  bundle = true
  minify = false
[build.processing.html]
  pretty_urls = true
[build.processing.images]
  compress = true
