# Config for the Netlify Build Plugin: netlify-plugin-fetch-feeds
[build]
  base = "website"
  command = "npm i && (npm run fetch; npm run build)"
  publish = "dist"

[[redirects]]
  # Redirect default Netlify subdomain to primary domain
  from = "https://events.datproject.org"
  to = "https://events.dat.foundation"
  status = 301
  force = true

[[redirects]]
  # Redirect default Netlify subdomain to primary domain
  from = "https://events.datproject.org/*"
  to = "https://events.dat.foundation/:splat"
  status = 301
  force = true

[[redirects]]
  # Redirect default Netlify subdomain to primary domain
  from = "https://dat-events.netlify.app"
  to = "https://events.dat.foundation/:splat"
  status = 301
  force = true

[[redirects]]
  # Redirect default Netlify subdomain to primary domain
  from = "https://dat-events.netlify.app/*"
  to = "https://events.dat.foundation/:splat"
  status = 301
  force = true

[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = true
  minify = false
[build.processing.js]
  bundle = true
  minify = false
[build.processing.html]
  pretty_urls = true
[build.processing.images]
  compress = true

[[plugins]]
  package = "/plugins/pretalx-fetch"

  [plugins.inputs]
    # Where should data files reside
    targetDomain = "events.dat.foundation"
    ttl = 60 # cache for 1 minute

    # All the feeds we wish to gather for use in the build

    [[plugins.inputs.conferences]]
      domain = "conf.consento.org"
      prefix = "2020"
      event = "dat-event-2020"
